Repository protofire/livepeer-alerts-backend, pull requests merged in 2019-07, with the labels that each got.

#63 (Feature) Refactors delegate called reward calculation on telegram jobs
  server/helpers/sendTelegramClaimRewardCall.js
  server/jobs/running-bot-telegram.js
Labels: enhancement

#76 [Bug] Fix unsubscribe link
  CHANGELOG.md
  package.json
  server/helpers/sendDelegatorEmail.js
Labels: bug

#81 [Task] Improve Changelog description
  CHANGELOG.md
Labels: enhancement

#86 (Feature) Delegator endpoint
  server/delegator/delegator.controller.js
  server/delegator/delegator.route.js
  utils/livepeer-alerts-backend.postman_collection.json
Labels: enhancement

#116 [Feature]Be notified when the UNBONDING > UNBONDED period has ended
  server/helpers/notification/notificateDelegatorUtils.js
  server/helpers/sendDelegatorEmail.js
  server/subscriber/subscriber.model.js
  test/notificate-delegators-utils.test.js
Labels: backend

#118 [Feature] Be notified when the Pending > Bonded period has ended
  server/helpers/notification/notificateDelegatorUtils.js
  server/helpers/notification/notificationUtils.js
  server/helpers/sendDelegatorTelegram.js
  server/helpers/telegramUtils.js
  server/notifications/telegram/delegator-bonding-period-has-ended/notification-bonding-period-has-ended.hbs
  server/subscriber/subscriber.controller.js
  server/subscriber/subscriber.model.js
  test/notificate-delegators-utils.test.js
Labels: backend
