Repository protofire/livepeer-alerts-backend, pull requests merged in 2019-01, with the labels that each got.

#3 [Feat] - Project Setup Backend
  .env.example
  .eslintignore
  .eslintrc
  .gitattributes
  .gitignore
  .istanbul.yml
  .prettierrc.json
  .travis.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  Procfile
  README.md
  config/config.js
  config/express.js
  config/mongoose.js
  config/param-validation.js
  config/winston.js
  index.js
  index.route.js
  package-lock.json
  package.json
  server/earning/earning.controller.js
  server/earning/earning.model.js
  server/earning/earning.route.js
  server/emails/templates/activation.hbs
  server/emails/templates/notification_success.hbs
  server/emails/templates/notification_warning.hbs
  server/helpers/APIError.js
  server/helpers/livepeerAPI.js
  server/helpers/sendEmail.js
  server/helpers/utils.js
  server/jobs/clear-documents.js
  server/jobs/send-notification.js
  server/subscriber/subscriber.controller.js
  server/subscriber/subscriber.model.js
  server/subscriber/subscriber.route.js
  test/misc.test.js
  test/subscriber.test.js
  utils/livepeer-alerts-backend.postman_collection.json
Labels: awaiting for review

#8 Added README and API files
  .eslintignore
  API.md
  README.md
Labels: awaiting for review, review

#9 [Hotfix] Fixed url link format on readme
  README.md
Labels: awaiting for review

#10 Hotfix/job exception
  README.md
  package.json
  server/helpers/sendEmail.js
Labels: Approved

#13 Add email templates from sendgrid
  .env.example
  config/config.js
  server/helpers/sendEmail.js
  server/notifications/emails/sendgrid_templates/20190114_staking-alert-all-good_HTML.txt
  server/notifications/emails/sendgrid_templates/20190114_staking-alert-pay-attention_HTML.txt
  server/notifications/emails/sendgrid_templates/README.md
Labels: review
